name = "GWGrids"
uuid = "d33f57a8-936b-4b85-ac63-7cab154bb436"
version = "0.1.0"
authors = ["vcantarella <vcantarella@gmail.com>"]

[deps]
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
SimplexGridFactory = "57bfcd06-606e-45d6-baf4-4ba06da0efd5"

[compat]
ExtendableGrids = "1.16.0"
JET = "0.11.3"
SimplexGridFactory = "2.6.1"
Test = "1.11.0"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JET"]
