# src/grid_types.jl

abstract type AbstractGWGrid end

# ==============================================================================
# 1. UNIFORM GRID (Regular spacing)
# ==============================================================================
struct UniformGrid{T<:AbstractFloat} <: AbstractGWGrid
    origin::NTuple{3, T}
    spacing::NTuple{3, T}
    dims::NTuple{3, Int}
end

# Usage: UniformGrid((0.0,0.0,0.0), (1.0,1.0,1.0), (100,100,50))

@inline function get_xyz(g::UniformGrid, I::CartesianIndex{3})
    # Math-based calculation: 0 memory loads
    # I[1]=i (x), I[2]=j (y), I[3]=k (z) - Adjust order if your convention differs
    x = g.origin[1] + (I[1] - 1) * g.spacing[1]
    y = g.origin[2] + (I[2] - 1) * g.spacing[2]
    z = g.origin[3] + (I[3] - 1) * g.spacing[3]
    return x, y, z
end

grid_size(g::UniformGrid) = g.dims

# ==============================================================================
# 2. RECTILINEAR GRID (Variable spacing, orthogonal)
# ==============================================================================
struct RectilinearGrid{T, V<:AbstractVector{T}} <: AbstractGWGrid
    x::V # Cell centers or nodes in X
    y::V # Cell centers or nodes in Y
    z::V # Cell centers or nodes in Z
end

@inline function get_xyz(g::RectilinearGrid, I::CartesianIndex{3})
    # 3 independent memory loads (Fast)
    return g.x[I[1]], g.y[I[2]], g.z[I[3]]
end

grid_size(g::RectilinearGrid) = (length(g.x), length(g.y), length(g.z))

# ==============================================================================
# 3. STRUCTURED GRID (Deformed Z / Stratigraphic)
# ==============================================================================
struct StructuredGrid{T, V<:AbstractVector{T}, A<:AbstractArray{T, 3}} <: AbstractGWGrid
    x::V # Regular X coordinates
    y::V # Regular Y coordinates
    z::A # Full 3D array for Z (e.g., from wiggly_layers)
end

@inline function get_xyz(g::StructuredGrid, I::CartesianIndex{3})
    # Hybrid: Math/Lookup for X/Y, Full Lookup for Z
    return g.x[I[1]], g.y[I[2]], g.z[I]
end

grid_size(g::StructuredGrid) = size(g.z)

# ==============================================================================
# 4. UNSTRUCTURED GRID (Point Cloud / Mesh Centers via ExtendableGrids)
# ==============================================================================
import ExtendableGrids: ExtendableGrid, Coordinates, CellVolumes, FaceNodes, FaceCells, FaceVolumes, FaceNormals, CellFaces, CellNodes

"""
    UnstructuredGrid{T, I, M_T, M_I, V_T} <: AbstractGWGrid

A wrapper around `ExtendableGrid{T, I}` from the `ExtendableGrids.jl` package,
representing an unstructured mesh (e.g., generated by `SimplexGridFactory.jl`).
It extracts and pre-computes connectivity and geometry arrays required for Finite Volume Method (FVM) calculations.
"""
struct UnstructuredGrid{T, I, M_T, M_I, V_T} <: AbstractGWGrid
    grid::ExtendableGrid{T, I}
    
    # Pre-extracted and computed properties for FVM
    n_nodes::Int
    n_cells::Int
    n_faces::Int

    coordinates::M_T     # dim x n_nodes
    cell_nodes::M_I      # nodes_per_cell x n_cells
    cell_centers::M_T    # dim x n_cells
    cell_volumes::V_T    # n_cells
    
    face_nodes::M_I      # nodes_per_face x n_faces
    face_cells::M_I      # 2 x n_faces
    face_areas::V_T      # n_faces (FaceVolumes in ExtendableGrids)
    face_normals::M_T    # dim x n_faces
    cell_faces::M_I      # faces_per_cell x n_cells
end

function UnstructuredGrid(egrid::ExtendableGrid{T, I}) where {T, I}
    coords = egrid[Coordinates]
    c_nodes = egrid[CellNodes]
    
    # Compute cell centers as the barycenter of their nodes
    dim = size(coords, 1)
    n_cells = size(c_nodes, 2)
    nodes_per_cell = size(c_nodes, 1)
    
    c_centers = zeros(T, dim, n_cells)
    for c in 1:n_cells
        for n in 1:nodes_per_cell
            node_idx = c_nodes[n, c]
            for d in 1:dim
                c_centers[d, c] += coords[d, node_idx]
            end
        end
        for d in 1:dim
            c_centers[d, c] /= nodes_per_cell
        end
    end
    
    n_nodes = size(coords, 2)
    
    # Extract existing properties needed for FVM from ExtendableGrids
    # This automatically triggers computation within ExtendableGrids if they are not already cached
    c_volumes = egrid[CellVolumes]
    f_nodes = egrid[FaceNodes]
    f_cells = egrid[FaceCells]
    f_areas = egrid[FaceVolumes]
    f_normals = egrid[FaceNormals]
    c_faces = egrid[CellFaces]
    
    n_faces = size(f_nodes, 2)

    M_T = typeof(coords)
    M_I = typeof(c_nodes)
    V_T = typeof(c_volumes)

    return UnstructuredGrid{T, I, M_T, M_I, V_T}(
        egrid,
        n_nodes, n_cells, n_faces,
        coords, c_nodes, c_centers, c_volumes,
        f_nodes, f_cells, f_areas, f_normals, c_faces
    )
end

# --- Handling Linear Indices for Unstructured Grid ---

# Case A: Kernel is launched with 1D range -> i is Int
# Returns the coordinates of the *node* at index i
@inline function get_xyz(g::UnstructuredGrid, i::Int)
    coords = g.coordinates
    dim = size(coords, 1)
    x = coords[1, i]
    y = dim >= 2 ? coords[2, i] : zero(x)
    z = dim >= 3 ? coords[3, i] : zero(x)
    return x, y, z
end

# Case B: Kernel is launched with 1D range -> I is CartesianIndex{1}
@inline function get_xyz(g::UnstructuredGrid, I::CartesianIndex{1})
    return get_xyz(g, I[1])
end

# Case C: User tries to access with 3D index (Error, or map if you had a 3D->1D map)
# Intentionally undefined to throw error

grid_size(g::UnstructuredGrid) = (g.n_nodes,)